### PR TITLE
Updating to latest version

### PR DESCRIPTION
**Pull request by beckler**

### CODE REVIEW

**Comment by brandon-beacher** [comment]
Could we use the official repo rather than our own fork @beckler ?

**Comment by beckler** [comment]
Yes... but we can't version it.
We we're pointing at: https://github.com/philly-d/ionic-plugin-deploy

**Comment by beckler** [comment]
@brandon-beacher ^

**Comment by brandon-beacher** [comment]
It looks like Phil actually made some commits to that fork - are we losing his work by switching?

https://github.com/philly-d/ionic-plugin-deploy/commits/deploy-persistence-patch

**Comment by beckler** [comment]
Technically yes, but whenever he fixed it, he filed an issue which has been resolved.

https://github.com/driftyco/ionic-plugin-deploy/issues/60

**Comment by brandon-beacher** [comment]
Awesome... So if we use the official repo - we can't version it - but we also get fixes? That seems like a risk worth taking?

**Pull request merged**
